#!/usr/bin/env python
#
# Call the command line interface for Epydoc.
#

# Make sure that we don't get confused between an epydoc.py script and
# the real epydoc package.
from os.path import abspath
import sys
script_path = abspath(sys.path[0])
sys.path = [p for p in sys.path if abspath(p) != script_path]

from epydoc.cli import cli
cli()
