name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: akaihola/darker@action_debug
        with:
          options: "--check --diff -l 120 -vvvvv"
          src: "./src"
